=== slosd/guiconfig/src/content/preferences.xsd
<?xml version="1.0"?>
<!--
    Copyright (C) 2014, 2015 Thomas Leberbauer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:p="http://guiconfig.freedig.org/preferences"
        targetNamespace="http://guiconfig.freedig.org/preferences"
        elementFormDefault="qualified">

<!-- represents any kind of integer or float number -->
<simpleType name="number-type">
  <restriction base="string">
    <pattern value="[+-]*[0-9]+\.?[0-9]*" />
  </restriction>
</simpleType>

<!-- platforms to filter by -->
<simpleType name="platform-type">
  <restriction base="string">
    <enumeration value="WINNT" />
    <enumeration value="Linux" />
    <enumeration value="Darwin" />
  </restriction>
</simpleType>

<!-- data type of preferences -->
<simpleType name="preference-type">
  <restriction base="string">
    <enumeration value="int" />
    <enumeration value="bool" />
    <enumeration value="string" />
  </restriction>
</simpleType>

<!-- label attribute -->
<attributeGroup name="labeled">
  <attribute name="label" type="string" use="required" />
</attributeGroup>


<!-- label and description attribute -->
<attributeGroup name="informative">
  <attributeGroup ref="p:labeled" />
  <attribute name="description" type="string" use="required" />
</attributeGroup>

<!-- attributes to define the scope of a preference -->
<attributeGroup name="filterable">
  <attribute name="minVersion" type="string" />
  <attribute name="maxVersion" type="string" />
  <attribute name="platform" type="p:platform-type" />
</attributeGroup>

<!-- a container that only contains preferences or groups of preferences -->
<complexType name="flat-container">
  <sequence minOccurs="0" maxOccurs="unbounded">
    <choice>
      <element name="group" type="p:flat-container" />
      <element name="pref" type="p:preference" />
    </choice>
  </sequence>

  <attributeGroup ref="p:labeled" />
  <attributeGroup ref="p:filterable" />
  <attribute name="description" type="string" />
</complexType>

<!-- a container that contains more structured preferences -->
<complexType name="container">
  <complexContent>
    <extension base="p:flat-container">
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element name="concerns">
          <complexType>
            <sequence minOccurs="1" maxOccurs="unbounded">
              <element name="concern" type="p:container" />
            </sequence>

            <attributeGroup ref="p:filterable" />
          </complexType>
        </element>
      </sequence>
    </extension>
  </complexContent>
</complexType>

<!-- a container that holds a view definition for a preference -->
<complexType name="view-container">
  <sequence minOccurs="0" maxOccurs="unbounded">
    <choice>
      <element name="group">
        <complexType>
          <complexContent>
            <extension base="p:view-container">
              <attributeGroup ref="p:labeled" />
              <attribute name="description" type="string" />
            </extension>
          </complexContent>
        </complexType>
      </element>
      <element name="checkbox" type="p:view-element" />
    </choice>
  </sequence>
</complexType>

<!-- an element that describes a view of a preference -->
<complexType name="view-element">
  <attributeGroup ref="p:informative" />
  <attribute name="value" type="string" />
</complexType>

<!-- a type of presentation of a preference -->
<simpleType name="mode-type">
  <restriction base="string">
    <enumeration value="radio" />
    <enumeration value="select" />
    <enumeration value="color" />
    <enumeration value="file" />
  </restriction>
</simpleType>

<!-- a method that can be overridden -->
<simpleType name="override-type">
  <restriction base="string">
    <enumeration value="getValue" />
    <enumeration value="setValue" />
    <enumeration value="getPref" />
    <enumeration value="setPref" />
    <enumeration value="dependencies" />
  </restriction>
</simpleType>

<!-- a filter for an open-file dialog -->
<simpleType name="file-filter-type">
  <restriction base="string">
    <enumeration value="All" />
    <enumeration value="HTML" />
    <enumeration value="Text" />
    <enumeration value="Images" />
    <enumeration value="XML" />
    <enumeration value="XUL" />
    <enumeration value="Apps" />
    <enumeration value="AllowURLs" />
    <enumeration value="Audio" />
    <enumeration value="Video" />
  </restriction>
</simpleType>

<!-- a preference -->
<complexType name="preference">
  <sequence minOccurs="0" maxOccurs="unbounded">
    <choice>
      <element name="option">
        <complexType>
          <simpleContent>
            <extension base="string">
              <attributeGroup ref="p:labeled" />
              <attributeGroup ref="p:filterable" />
            </extension>
          </simpleContent>
        </complexType>
      </element>
      <element name="mode">
        <complexType>
          <choice maxOccurs="unbounded">
            <element name="filterExtension">
              <complexType>
                <attribute name="label" type="string" use="required" />
                <attribute name="value" type="string" use="required" />
              </complexType>
            </element>
            <element name="filterType">
              <complexType>
                <attribute name="value" type="p:file-filter-type" use="required" />
              </complexType>
            </element>
          </choice>

          <attribute name="name" use="required">
            <simpleType>
              <restriction base="string">
                <enumeration value="file" />
              </restriction>
            </simpleType>
          </attribute>
        </complexType>
      </element>
      <element name="behavior">
        <complexType>
          <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="override">
              <complexType>
                <simpleContent>
                  <extension base="string">
                    <attribute name="name" type="p:override-type" use="required" />
                  </extension>
                </simpleContent>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
      <element name="view" type="p:view-container" />
      <element name="dependency">
        <complexType>
          <attributeGroup ref="p:filterable" />
          <attribute name="key" type="string" use="required" />
          <attribute name="equals" type="string" />
          <attribute name="in" type="string" />
        </complexType>
      </element>
      <element name="binding">
        <complexType>
          <attribute name="key" type="string" />
          <attribute name="type" type="p:preference-type" />
        </complexType>
      </element>
    </choice>
  </sequence>

  <attributeGroup ref="p:filterable" />
  <attribute name="key" type="string" use="required" />
  <attribute name="label" type="string" />
  <attribute name="description" type="string" />
  <attribute name="type" type="p:preference-type" use="required" />
  <attribute name="mode" type="p:mode-type" />
  <attribute name="default" type="string" />
  <attribute name="minValue" type="p:number-type" />
  <attribute name="maxValue" type="p:number-type" />
  <attribute name="indent">
    <simpleType>
      <restriction base="string">
        <enumeration value="indent" />
      </restriction>
    </simpleType>
  </attribute>
  <attribute name="inverted">
    <simpleType>
      <restriction base="string">
        <enumeration value="inverted" />
      </restriction>
    </simpleType>
  </attribute>
  <attribute name="wrapper" type="string" />
</complexType>

<!-- document root -->
<element name="preferences">
  <complexType>
    <sequence minOccurs="0" maxOccurs="unbounded">
      <element name="category">
        <complexType>
          <complexContent>
            <extension base="p:container">
              <attribute name="icon" />
            </extension>
          </complexContent>
        </complexType>
      </element>
    </sequence>
  </complexType>

  <key name="pref-key">
    <selector xpath=".//p:pref" />
    <field xpath="@key" />
  </key>
  <keyref name="pref-key-ref" refer="p:pref-key">
    <selector xpath=".//p:dependency" />
    <field xpath="@key" />
  </keyref>
</element>

</schema>

=== slosd/guiconfig/src/content/preferences.xml
<?xml version="1.0" ?>
<!DOCTYPE preferences SYSTEM "chrome://guiconfig/locale/options.dtd">
<preferences xmlns="http://guiconfig.freedig.org/preferences"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://guiconfig.freedig.org/preferences preferences.xsd">
  <category label="&accessibility;" icon="accessibility">
    <concerns>
      <concern label="&mousebehaviour;">
        <concerns>
          <concern label="&mouseclick;">
            <group label="&middleclick;">
              <pref key="middlemouse.contentLoadURL"
                    label="&middlemouse_contentLoadURL_name;"
                    description="&middlemouse_contentLoadURL_description;"
                    type="bool" />
              <pref key="middlemouse.paste"
                    label="&middlemouse_paste_name;"
                    description="&middlemouse_paste_description;"
                    type="bool" />
            </group>
            <group label="&urlbar;">
              <pref key="browser.urlbar.clickSelectsAll"
                    label="&browser_urlbar_clickSelectsAll_name;"
                    description="&browser_urlbar_clickSelectsAll_description;"
                    type="bool" />
              <pref key="browser.urlbar.doubleClickSelectsAll"
                    label="&browser_urlbar_doubleClickSelectsAll_name;"
                    description="&browser_urlbar_doubleClickSelectsAll_description;"
                    type="bool" />
            </group>
          </concern>
          <concern label="&mousescrollvertical;" minVersion="17.0b1">
            <group label="&mousescrollnone;">
              <pref key="mousewheel.default.action"
                    label="&mousewheel_action_name;"
                    description="&mousewheel_action_description;"
                    type="int"
                    mode="select">
                <option label="&mousewheel_action_o1;">0</option>
                <option label="&mousewheel_action_o2;">1</option>
                <option label="&mousewheel_action_o3;">2</option>
                <option label="&mousewheel_action_o4;">3</option>
              </pref>
            </group>
            <group label="&mousescrollshift;">
              <pref key="mousewheel.with_shift.action"
                    label="&mousewheel_action_name;"
                    description="&mousewheel_action_description;"
                    type="int"
                    mode="select">
                <option label="&mousewheel_action_o1;">0</option>
                <option label="&mousewheel_action_o2;">1</option>
                <option label="&mousewheel_action_o3;">2</option>
                <option label="&mousewheel_action_o4;">3</option>
              </pref>
            </group>
            <group label="&mousescrollstrg;">
              <pref key="mousewheel.with_control.action"
                    label="&mousewheel_action_name;"
                    description="&mousewheel_action_description;"
                    type="int"
                    mode="select">
                <option label="&mousewheel_action_o1;">0</option>
                <option label="&mousewheel_action_o2;">1</option>
                <option label="&mousewheel_action_o3;">2</option>
                <option label="&mousewheel_action_o4;">3</option>
              </pref>
            </group>
            <group label="&mousescrollalt;">
              <pref key="mousewheel.with_alt.action"
                    label="&mousewheel_action_name;"
                    description="&mousewheel_action_description;"
                    type="int"
                    mode="select">
                <option label="&mousewheel_action_o1;">0</option>
                <option label="&mousewheel_action_o2;">1</option>
                <option label="&mousewheel_action_o3;">2</option>
                <option label="&mousewheel_action_o4;">3</option>
              </pref>
            </group>
          </concern>
        </concerns>
      </concern>
      <concern label="&urlbar;" minVersion="3.0">
        <pref key="browser.urlbar.default.behavior"
              type="int"
              minVersion="3.5"
              maxVersion="35.*">
          <behavior>
            <override name="setValue">
            <![CDATA[
              var checkboxes = view.getElementsByTagName('checkbox');
              for(var i = 0, l = checkboxes.length, checkbox; i < l; i++) {
                checkbox = checkboxes[i];
                checkbox.checked = parseInt(value) & parseInt(checkbox.getAttribute('value'));
              }
            ]]>
            </override>
            <override name="getValue">
            <![CDATA[
              var bitmap = 0;
              var checkboxes = view.getElementsByTagName('checkbox');
              for(var i = 0, l = checkboxes.length, checkbox; i < l; i++) {
                checkbox = checkboxes[i];
                if(checkbox.checked) {
                  bitmap += parseInt(checkbox.getAttribute('value'));
                }
              }
              return bitmap;
            ]]>
            </override>
          </behavior>
          <view>
            <group label="&urlbar_restrict_name;">
              <checkbox label="&browser_urlbar_restrict_typed_name;"
                        description="&browser_urlbar_restrict_typed_description;"
                        value="32" />
              <checkbox label="&browser_urlbar_restrict_history_name;"
                        description="&browser_urlbar_restrict_history_description;"
                        value="1" />
              <checkbox label="&browser_urlbar_restrict_bookmark_name;"
                        description="&browser_urlbar_restrict_bookmark_description;"
                        value="2" />
              <checkbox label="&browser_urlbar_restrict_tag_name;"
                        description="&browser_urlbar_restrict_tag_description;"
                        value="4" />
            </group>
            <group label="&urlbar_match_name;">
              <checkbox label="&browser_urlbar_match_title_name;"
                        description="&browser_urlbar_match_title_description;"
                        value="8" />
              <checkbox label="&browser_urlbar_match_url_name;"
                        description="&browser_urlbar_match_url_description;"
                        value="16" />
            </group>
          </view>
        </pref>
        <pref key="browser.urlbar.suggest.history.onlyTyped"
              label="&browser_urlbar_restrict_typed_name;"
              description="&browser_urlbar_restrict_typed_description;"
              type="bool"
              minVersion="36" />
        <pref key="browser.urlbar.matchBehavior"
              label="&browser_urlbar_matchBehavior_name;"
              description="&browser_urlbar_matchBehavior_description;"
              type="int"
              mode="select">
          <option label="&browser_urlbar_matchBehavior_o1;">0</option>
          <option label="&browser_urlbar_matchBehavior_o2;">1</option>
          <option label="&browser_urlbar_matchBehavior_o3;">2</option>
          <option label="&browser_urlbar_matchBehavior_o4;" minVersion="3.0">3</option>
        </pref>
        <pref key="browser.urlbar.maxRichResults"
              label="&browser_urlbar_maxRichResults_name;"
              description="&browser_urlbar_maxRichResults_description;"
              type="int" />
        <pref key="browser.urlbar.autoFill"
              label="&browser_urlbar_autoFill_name;"
              description="&browser_urlbar_autoFill_description;"
              type="bool" />
        <pref key="browser.fixup.alternate.enabled"
              label="&browser_fixup_alternate_enabled_name;"
              description="&browser_fixup_alternate_enabled_description;"
              type="bool" />
        <pref key="browser.fixup.alternate.prefix"
              label="&browser_fixup_alternate_prefix_name;"
              description="&browser_fixup_alternate_prefix_description;"
              type="string"
              indent="indent">
          <dependency key="browser.fixup.alternate.enabled" equals="true" />
        </pref>
        <pref key="browser.fixup.alternate.suffix"
              label="&browser_fixup_alternate_suffix_name;"
              description="&browser_fixup_alternate_suffix_description;"
              type="string"
              indent="indent">
          <dependency key="browser.fixup.alternate.enabled" equals="true" />
        </pref>
      </concern>
      <concern label="&websites;">
        <group label="&accessibility_typeaheadfind_label;">
          <pref key="accessibility.typeaheadfind.casesensitive"
                label="&accessibility_typeaheadfind_casesensitive_name;"
                description="&accessibility_typeaheadfind_casesensitive_description;"
                type="int"
                mode="select"
                minVersion="3.0">
            <option label="&accessibility_typeaheadfind_casesensitive_o1;">-1</option>
            <option label="&accessibility_typeaheadfind_casesensitive_o2;">0</option>
            <option label="&accessibility_typeaheadfind_casesensitive_o3;">1</option>
          </pref>
          <pref key="accessibility.typeaheadfind.timeout"
                label="&accessibility_typeaheadfind_timeout_name;"
                description="&accessibility_typeaheadfind_timeout_description;"
                type="int" />
        </group>
        <group label="&misc;">
          <pref key="prompts.tab_modal.enabled"
                label="&prompts_tab_modal_enabled_name;"
                description="&prompts_tab_modal_enabled_description;"
                type="bool"
                minVersion="4.0" />
          <pref key="signon.autofillForms"
                label="&signon_prefillForms_name;"
                description="&signon_prefillForms_description;"
                type="bool"/>
